### ISSUE TITLE
MicroLogix 1400

### ISSUE THREAD

**Issue by AlexDraco** [digitalpetri/ethernet-ip#42]
Does this work with the micrologix 1400? I cant seem to get it to work, Ethernet/IP returns some information from the PLC

productName=1766-L32BWA B/13.00
revisionMajor=2
revisionMinor=13

but can read/write anything

**Comment by kevinherron** [comment]
I think to read from a MicroLogix you'd need to encapsulate DF1 commands using services on the PCCC object. These are not implemented by this library, though they could be implemented in theory, much like the Logix services currently are.

**Comment by AlexDraco** [comment]
Could you point me in the direction of how to achieve this? Or is there a better way to get Ethernet Communication with ML1400?
Thanks btw

**Comment by kevinherron** [comment]
DF1 is documented [here](https://literature.rockwellautomation.com/idc/groups/literature/documents/rm/1770-rm516_-en-p.pdf), but I'm afraid I don't have any additional information or source of documentation for how to use the PCCC object or otherwise communicate directly with a MicroLogix. It's not something I've implemented before.

**Comment by kevinherron** [comment]
Oh, for what it's worth, I think there's also a way to do it without the PCCC object, but again I don't actually have any details on how that works. I do know DF1 is still involved.
