### ISSUE TITLE
Examples of reading (cyclically) and writing UDTs and ARRAYs?

### ISSUE THREAD

**Issue by WimVriend** [digitalpetri/ethernet-ip#48]
![CONSTANTS_UDT](https://user-images.githubusercontent.com/46961736/139253564-d6f027fd-e83a-40ba-bd95-9d5dc85b0e33.png)
![CM_STATUS_UDT](https://user-images.githubusercontent.com/46961736/139253568-9ff72f2e-c853-4c60-b637-88f4d9c635f0.png)

Hello Kevin and others,

I have been granted the challenging task of creating a communication driver for our Java based software, to communicate with a new RSLogix PLC. In the PLC we use Controller Tags to store the Control Module statuses, commands, constants etcetera. Basically we have recreated the structures we also use for our Siemens PLC's.

My task is to build a prototype using the cip-client and my question is: are there any examples of how to read an UDT cyclically (say, every 0.25 sec) and where can I find them? I would expect that the cip-client was tested with use-cases like mine?

To elaborate a bit further. The CM_STATUS UDT contains one UDT per Control Module, which holds the BOOLEAN status-bits (no other types of data). It would be great if the whole STRUCT could be read 'in one go' and the entire STRUCT translated into an array of bytes in Java.

The other STRUCTs (like CONSTANTS) contain an array of DINTS per Control Module. These should be read and written per Control Module.

Of course I do not expect you to do my programming for me, but any help is appreciated!

**Comment by WimVriend** [comment]
OK, I understand that there may be a 'conflict of interests', but from my point of view (and from the repos') it's also important to have good examples...

Another noob question. I understand that Ethernet/IP uses CIP to communicate. So i would assume that when you know you are going to communicate with an RSLogix controller, you 'should' use the Ethernet/IP client rather than the CIP client?

The reason this question pops up, is that the only example concerning the Ethernet/IP client does NOT include reading or writing tags (which is the main reason to communicate, isn't it?). Would it be possible to add some lines of code to that example, to read and write some tag(s)?

BTW, did you receive my PM?

**Comment by kevinherron** [comment]
I got your email but I haven't had a chance to respond.

It sounds like you know what tags and UDTs you want to read ahead of time. If this is the case I can help you a little, because as I mentioned the existing example in the `cip-services` README already shows you how to read a tag. If you need to know more you'll have to be more specific and ask bite-sized questions.

> Another noob question. I understand that Ethernet/IP uses CIP to communicate. So i would assume that when you know you are going to communicate with an RSLogix controller, you 'should' use the Ethernet/IP client rather than the CIP client?

CIP defines the objects and services on top of EtherNet/IP. You'll want to use `CipClient` when communicating with a Logix controllers. 

I don't have any free time to dedicate to creating examples and documentation for this library right now so if this project will need a lot of hand holding then maybe you should look for a commercial alternative that comes with a support contact. I would also suggest you become an ODVA member and get access to the EtherNet/IP specifications if you aren't already.

**Comment by WimVriend** [comment]
Hello Kevin,

That's clear: I will dig into the CIP documentation and will give it a go. Given the fact that we indeed 'know' all tags in advance, it should not be too difficult. The only thing I am a bit uncertain of is error-handling. 

I don't think hand-holding is necessary (even unwise in this time of corona). It's just that in Holland we do ride bikes a lot and a push-start is always nice! Again, thanks for all your effort.
